[package]
name = "file_manager"
version = "0.1.0"
edition = "2021"
authors = ["Ilyas Zanan"]
description = "A simple CLI file manager."

[dependencies]
clap = "4.0"
walkdir = "2.4.0"
dirs = "5.0"
whoami = "1.2"
colored = "2.0"
figlet-rs = "0.1"

[features]
default = ["cli"]
cli = []
